### ISSUE TITLE
Little feedback?

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/enhanced-object-instance#1]
Hi @Ocramius ,

sorry for pinging/adding you to this repo, but since you are the creator of the `ProxyManager` i though it's a good idea to get your oppinion on this, before i make it public.

What you think about this little (prototype) proxy wrapper for log/cache (any maybe for other things like tracing, ...)
https://github.com/ThaDafinser/UglyProxyManagerFun

More information in the README.md or test.php

**Comment by Ocramius** [comment]
Hey @ThaDafinser, I'll read through this later this week - will be at Confoo this week...

**Comment by ThaDafinser** [comment]
No problem. Have fun at Confoo :-)

**Comment by ThaDafinser** [comment]
I added now some tests for PSR caching, i think this is pretty basic and should work  https://github.com/ThaDafinser/UglyProxyManagerFun/blob/master/tests/unit/EnhanceInstanceTest.php#L36-L101

Next step will be PSR logging refactoring
- [ ] what shall be logged (maybe a formatter, but no good idea until yet)
- [ ] execution time
- [ ] pre call (with parameters)
- [ ] post call (with parameters + result + time)
- [ ] post + cache call (when the post call is a cache call)
- [ ] Exception after pre? how to log that?
- [ ] ...dunno

**Comment by ThaDafinser** [comment]
Issues will be seperated in multiple
